### ISSUE TITLE
Release Checklist

### ISSUE THREAD

**Issue by peitek** [brains-on-code/eyetracking-linearity-replication#1]
After acceptance of the paper, we still need to provide the following things:

- [ ] Update Abstract
- [ ] Add link to preprint
- [ ] Finalize data/scripts for analysis
- [ ] Update URL
- [ ] Add to our brains-on-code-website
- [ ] Add font size to stimuli (for easier replications)
